version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    restart: always
    volumes:
      - /etc/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"